name: release-semver-version

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/semver-version.yml"
  workflow_dispatch:

permissions:
  packages: write
  contents: write # needed for the semver action
  actions: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  version:
    uses: ./.github/workflows/semver-version.yml
    with:
      prefix: "semver-versioning"
