name: Release Semver Version

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/semver-version.yml"
  workflow_dispatch:
    inputs:
      create_tag:
        description: "Create a Git tag and release"
        default: false
        type: boolean

permissions:
  packages: write
  contents: write # needed for the semver action
  actions: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  version:
    uses: ./.github/workflows/semver-version.yml
    with:
      prefix: "semver-versioning"
      suppress_tag: ${{ ((github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && inputs.create_tag)) != true }}
